### ISSUE TITLE
Deduplicate

### ISSUE THREAD

**Issue by jmhobbs** [ying17/rpleditor#3]
Rdio will let you add the same song to a playlist twice.  I understand why, but sometimes when I'm building a playlist, I do it on accident.

It would be great if the editor could automatically pull out duplicate songs.

**Comment by ying17** [comment]
Hi there! I haven't been monitoring the project and didn't have notifications so I didn't see your issues/pull requests!

I've made some changes to the code, would you mind re-applying your changes against the new code base :)
